### ISSUE TITLE
代码无法运行

### ISSUE THREAD

**Issue by bluecatblue** [BearBiscuit05/S5P#2]
您好，您提供的代码无法运行，如果可以的话，能否更新一版可以运行的代码并给出用例。（文章中对于2PS-L的结果展示跟源代码运行结果好像有一些出入）

**Comment by BearBiscuit05** [comment]
您可以提供无法运行的相关报错吗，一般来说，在完成编译之后，仅需要修改cpp/project.properties的文件，调整对应数据集的相关信息，便可以开始运行。
关于2PS的展示，具体的区别在什么地方可以更加清晰的描述一下吗？

**Comment by bluecatblue** [comment]
int TGEngine::readline(std::pair<int, int> &edge) 在运行的时候就会越界

**Comment by BearBiscuit05** [comment]
这个问题我认为可能是数据集的边数目与配置文件中写的数目不对应导致的。由于国庆节不在实验室，后续可能我们也会在运行一下这个程序。你也可以关注https://github.com/BearBiscuit05/partition_baseline了解更多基线信息。
